### ISSUE TITLE
Finetune script

### ISSUE THREAD

**Issue by JinyuanSun** [evo-design/evo#11]
Could you provide a script/notebook demo to show how to finetune this model?

**Comment by philippbayer** [comment]
Here's how I just did it, would be curious to see if there's anything model-specific I can use to make the training go faster. I ran into a bunch of issues, see comments.

I had to use a single letter for the padding (N instead of [PAD]), I had to split my fastas into pieces of 500bp or the A100 would run out of memory.

I'm using mitogenome pieces of fastas of fish; not prokaryotes but of prokaryotic origin :) 

```
import torch
print(torch.cuda.is_available())
from transformers import AutoConfig, AutoModelForCausalLM, TrainingArguments, Trainer
from transformers import AutoTokenizer, DataCollatorForLanguageModeling
from datasets import Dataset, load_dataset, DatasetDict
from Bio import SeqIO

# they used the 1-8k base model as a start for finetuning, so let's do the same for now
model_name = 'togethercomputer/evo-1-8k-base'

model_config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=model_config,
    trust_remote_code=True,
)

tokenizer = AutoTokenizer.from_pretrained("togethercomputer/evo-1-8k-base",
        trust_remote_code=True)

## make a Dataset from my local data

with open('all_fastas.csv', 'w') as out_fh:
    out_fh.write('ID,Seq\n')
    for x in SeqIO.parse('12S.v0.10.16S.v0.4.Mitogenomes.v0.1.fasta', 'fasta'):
        full_seq = str(x.seq)
        # splitting the sequences in pieces of 500bp so the A100 doesn't run out of memory
        full_seq_split = [full_seq[i:i+500] for i in range(0, len(full_seq), 500)]
        for counter, i in enumerate(full_seq_split):
            out_fh.write(f'{x.id}_{counter},{i}\n')

train_ds = load_dataset('csv', data_files = 'all_fastas.csv')

def preprocess_function(text):
    return tokenizer(text['Seq'])

tokenized_ds = train_ds.map(
    preprocess_function,
    batched=True,
    num_proc=4,
)

train_testvalid = tokenized_ds['train'].train_test_split(test_size=0.2)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

tokenizer.pad_token = "N" # crashes without a padding token (saying I need a padding token)
# but Evo runs ord() on the padding token and ord() can only use single characters. Normally people use [PAD], let's just use N

training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    # runs out of memory with the default batch_size
    per_device_train_batch_size = 4
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_testvalid["train"],
    eval_dataset=train_testvalid["test"],
    data_collator=data_collator,
)

trainer.train()

print(trainer.evaluate())

trainer.save_model('./finetuned.model')
```

Load the model via from_pretrained('./finetuned.model'). It's still finetuning and a bit slow; will take about 50 hours for 304,354 pieces of DNA of length 500 bp that come from 64,573 mitogenomes and 12S/16S pieces (total size: 140Mb)

**Comment by JinyuanSun** [comment]
@philippbayer Nice job! I also found there are no special token in this tokenizer, but the paper says they used EOS tokens to split individual DNA sequences.

**Comment by JinyuanSun** [comment]
@philippbayer I tried to use bf16, seems to work. Another way might be freezing some layers. I am using Human cds sequences to finetune the last layer. Not sure will the Hyena works like Transformers that finetune some layers can work. But this allow me to finetune `evo` on **one RTX 4090** and largely increased the sequence length to 3000 nt. 
```python
import transformers
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from transformers import AutoConfig, TrainingArguments, Trainer
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["WANDB_DISABLED"] = "true"

model_name = 'togethercomputer/evo-1-8k-base'

model_config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)
model_config.use_cache = False

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=model_config,
    trust_remote_code=True,
    device_map={"":0},
    torch_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = "X"

# frezze most parameters
for p in model.parameters():
    p.requires_grad = False

for p in model.backbone.blocks[-1].parameters():
    p.requires_grad = True

from datasets import load_dataset

dataset = load_dataset("gonzalobenegas/human-genome-cds")
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

def preprocess_function(sample):
    return tokenizer(sample['seq'], padding="longest", truncation=True, max_length=3000)

tokenized_ds = dataset.map(
    preprocess_function,
    batched=True,
    num_proc=12,
)

training_args = TrainingArguments(
    output_dir="./evo_results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    gradient_accumulation_steps=2,
    per_device_train_batch_size=4,
    warmup_steps=10,
    max_steps=100, # only a demo
    logging_steps=10,
    eval_steps=100,
    bf16=True
    # fp16=True, # This didn't work.
)


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["test"],
    data_collator=data_collator,
    
)

trainer.train()

```

**Comment by philippbayer** [comment]
Thanks!!! The freezing is great, it cut my finetuning town down from ~50 hours to ~14 hours which makes sense considering I'm retraining the entire thing :) I did ran out of space over night so don't forget to set your `save_total_limit = 3` :)

fp16 is very hardware-dependent, I just always turn it on as it promises faster training and less memory usage https://pytorch.org/blog/accelerating-training-on-nvidia-gpus-with-pytorch-automatic-mixed-precision/ might just be that your GPU doesn't support it.

With the freezing of most parameters the 'full' sequences which include entire mitogenomes still make my A100 run out of memory. I haven't run any experiments on what the 'longest' possible length is. I can use 5000 bp pieces without crashing.

**Comment by Zymrael** [comment]
This is all great. In the future (if there is sufficient interest) we are also going to support finetuning of Evo on the Together API, which hopefully will make it a lot easier to perform full model finetunes at full context (131k and beyond). 

There is also planned support of the architecture on other open frameworks for LLM finetuning.

**Comment by philippbayer** [comment]
I'd definitely be interested in that!!

**Comment by cclough** [comment]
> This is all great. In the future (if there is sufficient interest) we are also going to support finetuning of Evo on the Together API, which hopefully will make it a lot easier to perform full model finetunes at full context (131k and beyond).
> 
> There is also planned support of the architecture on other open frameworks for LLM finetuning.

interested!

**Comment by philippbayer** [comment]
Interestingly, freezing everything but the last layer as above in @JinyuanSun's script doesn't work well with my data:

![image](https://github.com/evo-design/evo/assets/413885/c20c1a43-d802-46a8-affa-cf7a929c1d4e)

As you can see, the training loss is identical.

Doing it 'my' way works better, but takes about three times the time (so far....)

![image](https://github.com/evo-design/evo/assets/413885/b17f1aec-a186-404a-91fe-93890eb700de)

I'm sure there's some optimal middle way where some, not all layers are finetuned.

**Comment by leonwyang** [comment]
Has anyone explored FSDP finetuning on multiple GPUs? I got error "ValueError: Must flatten tensors with uniform dtype but got torch.bfloat16 and torch.float32" Seems due to the fact FSDP requires the tensor dtype being uniform but stripedhyena is a mixed precision model?

**Comment by adrienchaton** [comment]
@leonwyang @philippbayer I am having the same issues as you ... here are the current status that I also face with my own data and finetuning codes (running on DGX A100 80GB)

- **FSDP** and **fused ADAM** cannot be used because of mixed dtypes ... I have not yet looked into model parallelism (MP), i.e. splitting the model over several GPUs if the desired context length goes OOM with DDP and per-device batch size = 1 ... **did anyone successfully use MP for finetuning Evo?**
- if leaving **all parameters learnable**, I can only fit around 500 tokens per device (regular DDP, batch size = 1 and then gradient accumulation) but the loss decreases smoothly
- if **freezing most parameters**, i.e. only finetuning the embedding and blocks 0+1+30+31 (i.e. two first/last), I can fit 7k tokens per device but then the loss doesnt decrease (probably because too many parameters are already learned and fixed?) ... the total batch size is >1M tokens

Before digging the option of model parallelism, I would like to look into more advanced parameter-efficient finetuning methods. Instead of freezing most of the layers (which seems to prevent the model to learn further), applying LoRA, IA3 or other PEFT methods could bring down the number trainable parameters to still fit enough context but hopefully the model can learn and decrease the loss on the finetuning sequence data.

@Zymrael did you experiment with applying the common PEFT methods to Stryped Hyena? E.g. https://huggingface.co/docs/peft/main/en/conceptual_guides/lora
I used it with more common architectures like ESM2 protein LMs and it was working nicely. But with Stryped Hyena, I am not sure which parameters should be left free, freeze or reparametrized with PEFT ... any advice here would be great, I will also let you know how my trials go with wrapping Evo in a PEFT model ... Ideally, proving that we can finetune at e.g. MSL = 7k bases with 80GB GPU (and decrease the loss, whereas freezing all 2-29 blocks would prevent learning).

**Comment by kawabata-tomoko** [comment]
Hello, I'm trying to finetuning this model with those script:
```python
import torch

from project.srcs.BaseModel import StripedHyenaModelForCausalLM, StripedHyenaPreTrainedModel
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer
from transformers import DataCollatorForLanguageModeling, Trainer, TrainingArguments

from datasets import load_dataset

configs=AutoConfig.from_pretrained(
    '/home/models/evo/evo-1-131k-base',
    trust_remote_code=True,
    use_cache=False
    )

model = AutoModelForCausalLM.from_pretrained(
    '/home/models/evo/evo-1-131k-base',
    config=configs,
    trust_remote_code=True,
    torch_dtype=torch.float16,
    device_map={"":0}
)

tokenizer=AutoTokenizer.from_pretrained(
    '/home/models/evo/evo-1-131k-base',
    trust_remote_code=True
    )

datacollator = DataCollatorForLanguageModeling(tokenizer=tokenizer,mlm=False)
training_args=TrainingArguments(
    output_dir="/home/models/project/models/finetuning/model1",
    evaluation_strategy="epoch",
    learning_rate= 2e-5,
    weight_decay=0.01,
    num_train_epochs=5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    bf16=True
)
train_ds = load_dataset("csv",data_files="/home/models/project/datasets/dataset_cas12.csv")
# Those sequences are only 500nt long.
def process_func(text):
    return tokenizer(text["Seq"],padding="longest")

tokenizer.pad_token = 'N'

tokenedtrain_ds=train_ds.map(process_func,batched=True,num_proc=4)["train"].train_test_split(test_size=0.3)
trainer= Trainer(
    model=model,
    args=training_args,
    train_dataset= tokenedtrain_ds["train"],
    eval_dataset= tokenedtrain_ds["test"],
    data_collator=datacollator
)

trainer.train()
```
This script is run on single A100 80Gb device, with set ` export CUDA_VISIBLE_DEVICES=0` . It's could normally train and evaluate with decrease loss value.
However,  when huggingface Trainer trying to save model, I'll get this error below:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2356, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2807, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2886, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 3454, in save_model
    self._save(output_dir)
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/trainer.py", line 3525, in _save
    self.model.save_pretrained(
  File "/home/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2793, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "/home/miniconda3/lib/python3.9/site-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/home/miniconda3/lib/python3.9/site-packages/safetensors/torch.py", line 477, in _flatten
    raise RuntimeError(
RuntimeError:
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'backbone.embedding_layer.weight', 'backbone.unembed.weight'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors
```
Even when using trainer.save_model("/home/models/project/models/finetuning/model1") or simply trainer.model.save_pretrained(...), the same error occurs. 
However, when I set the argument safe_serialization=False, I am able to save the model using trainer.model.save_pretrained(...). Therefore, I attempted to rewrite the save_pretrained method in the StripedHyenaPreTrainedModel class:
```python
def save_pretrained(
        self,
        save_directory: Union[str, os.PathLike],
        is_main_process: bool = True,
        state_dict: Optional[dict] = None,
        save_function: Callable = torch.save,
        push_to_hub: bool = False,
        max_shard_size: Union[int, str] = "5GB",
        safe_serialization: bool = True,
        variant: Optional[str] = None,
        token: Optional[Union[str, bool]] = None,
        save_peft_format: bool = True,
        **kwargs,
    ):
        super().save_pretrained(
            save_directory,
            is_main_process,
            state_dict,
            save_function,
            push_to_hub,
            max_shard_size,
            safe_serialization=False, # Just ignore this arg.
            variant=variant,
            token=token,
            save_peft_format=save_peft_format,
            **kwargs
        )
```
It has worked, but it still feels very unusual. Has anyone else encountered this issue before?
some packages i used :
Package                   Version

---
accelerate                0.32.1
biopython                 1.84
datasets                  2.21.0
einops                    0.8.0
eval_type_backport        0.2.0
evo-model                 0.1.2
flash-attn                2.5.9.post1
huggingface-hub           0.23.4
idna                      3.4
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.40
nvidia-nvtx-cu12          12.1.105
pandas                    2.0.3
rotary-emb                0.5.2
safetensors               0.4.2
scipy                     1.13.1
stripedhyena              0.2.2
together                  1.2.1
tokenizers                0.19.1
torch                     2.3.1
torchaudio                2.3.1
torchvision               0.18.1
transformers              4.44.2
triton                    2.3.1

**Comment by kawabata-tomoko** [comment]
> Thanks!!! The freezing is great, it cut my finetuning town down from ~50 hours to ~14 hours which makes sense considering I'm retraining the entire thing :) It also lets me increase my `per_device_train_batch_size` and `per_device_eval_batch_size` to 128 instead of 4 for a few more hours shaved off, now total train time is around 10 hours.
> 
> I did ran out of space over night so don't forget to set your `save_total_limit = 3`
> 
> fp16 is very hardware-dependent, I just always turn it on as it promises faster training and less memory usage https://pytorch.org/blog/accelerating-training-on-nvidia-gpus-with-pytorch-automatic-mixed-precision/ might just be that your GPU doesn't support it.
> 
> With the freezing of most parameters the 'full' sequences which include entire mitogenomes still make my A100 run out of memory. I haven't run any experiments on what the 'longest' possible length is. I can use 5000 bp pieces without crashing.



> ```python
> per_device_train_batch_size
> ```
Hello,

I am concerned that this might not work on my device. I can only fine-tune half the length (prompt+sequence~1100 tokens) of the 3000nt you mentioned on a single A800 80Gb GPU, and it will use 80319Mib of memory.

I have to use the minimal per_device_train_batch_size (just 1) and per_device_eval_batch_size (just 1), while using bf16 and freezing most parameters as your script does. How much memory does the evo model take during your tests? Could you provide more information about your script?

For more code details, please see: https://github.com/evo-design/evo/issues/11#issuecomment-2325493897

Thank you for your help!

**Comment by cclough** [comment]
> This is all great. In the future (if there is sufficient interest) we are also going to support finetuning of Evo on the Together API, which hopefully will make it a lot easier to perform full model finetunes at full context (131k and beyond).
> 
> There is also planned support of the architecture on other open frameworks for LLM finetuning.

any update on fine-tuning support @Zymrael?

**Comment by xiyang-aads-lilly** [comment]
@philippbayer  seems that your seq len is 500.  Have you tried large seq len like 8000 as the model max seq len?  I have tried to wrap the model with deepspeed and train with 8000 seq len, it always cause GPU OOM even with stage-3.

**Comment by philippbayer** [comment]
@xiyang-aads-lilly Yes I cut down the size to 500 bp when I kept on hitting memory limits on my A100. I didn't do much additional testing or different models, I just cut down my sequences until it worked :)

**Comment by Andyargueasae** [comment]
Just one question, have you guys experienced the problem that for each logging step, the train losses were all 0.0?
I have the same data format as @philippbayer:
ID,Seq
A.1, ATCG...

**Comment by baiwenhuim** [comment]
Excellent work! I have one question, do I have to use nucleotide as training data when fine-tuning evo? Do amino acids work?

**Comment by xuanwuji** [comment]
> [@philippbayer](https://github.com/philippbayer) I tried to use bf16, seems to work. Another way might be freezing some layers. I am using Human cds sequences to finetune the last layer. Not sure will the Hyena works like Transformers that finetune some layers can work. But this allow me to finetune `evo` on **one RTX 4090** and largely increased the sequence length to 3000 nt.
> 
> import transformers
> import torch
> from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
> from transformers import AutoConfig, TrainingArguments, Trainer
> import os
> 
> os.environ["CUDA_VISIBLE_DEVICES"] = "0"
> os.environ["WANDB_DISABLED"] = "true"
> 
> model_name = 'togethercomputer/evo-1-8k-base'
> 
> model_config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)
> model_config.use_cache = False
> 
> model = AutoModelForCausalLM.from_pretrained(
>     model_name,
>     config=model_config,
>     trust_remote_code=True,
>     device_map={"":0},
>     torch_dtype=torch.float16
> )
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> tokenizer.pad_token = "X"
> 
> # frezze most parameters
> for p in model.parameters():
>     p.requires_grad = False
> 
> for p in model.backbone.blocks[-1].parameters():
>     p.requires_grad = True
> 
> from datasets import load_dataset
> 
> dataset = load_dataset("gonzalobenegas/human-genome-cds")
> data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
> 
> def preprocess_function(sample):
>     return tokenizer(sample['seq'], padding="longest", truncation=True, max_length=3000)
> 
> tokenized_ds = dataset.map(
>     preprocess_function,
>     batched=True,
>     num_proc=12,
> )
> 
> training_args = TrainingArguments(
>     output_dir="./evo_results",
>     evaluation_strategy="epoch",
>     learning_rate=2e-5,
>     weight_decay=0.01,
>     gradient_accumulation_steps=2,
>     per_device_train_batch_size=4,
>     warmup_steps=10,
>     max_steps=100, # only a demo
>     logging_steps=10,
>     eval_steps=100,
>     bf16=True
>     # fp16=True, # This didn't work.
> )
> 
> 
> trainer = Trainer(
>     model=model,
>     args=training_args,
>     train_dataset=tokenized_ds["train"],
>     eval_dataset=tokenized_ds["test"],
>     data_collator=data_collator,
>     
> )
> 
> trainer.train()

@JinyuanSun  Hi Sun,  Thanks for the fine-tuning code. I used your code finetune a model and I got a results folder ./evo_result/checkpoint-100/  
Could you show how to read the model from the result and use it for the generation task? I was having some confusion loading the model. Thanks very much!

**Comment by JinyuanSun** [comment]
> > [@philippbayer](https://github.com/philippbayer) I tried to use bf16, seems to work. Another way might be freezing some layers. I am using Human cds sequences to finetune the last layer. Not sure will the Hyena works like Transformers that finetune some layers can work. But this allow me to finetune `evo` on **one RTX 4090** and largely increased the sequence length to 3000 nt.
> > import transformers
> > import torch
> > from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
> > from transformers import AutoConfig, TrainingArguments, Trainer
> > import os
> > os.environ["CUDA_VISIBLE_DEVICES"] = "0"
> > os.environ["WANDB_DISABLED"] = "true"
> > model_name = 'togethercomputer/evo-1-8k-base'
> > model_config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)
> > model_config.use_cache = False
> > model = AutoModelForCausalLM.from_pretrained(
> > model_name,
> > config=model_config,
> > trust_remote_code=True,
> > device_map={"":0},
> > torch_dtype=torch.float16
> > )
> > tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> > tokenizer.pad_token = "X"
> > # frezze most parameters
> > for p in model.parameters():
> > p.requires_grad = False
> > for p in model.backbone.blocks[-1].parameters():
> > p.requires_grad = True
> > from datasets import load_dataset
> > dataset = load_dataset("gonzalobenegas/human-genome-cds")
> > data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
> > def preprocess_function(sample):
> > return tokenizer(sample['seq'], padding="longest", truncation=True, max_length=3000)
> > tokenized_ds = dataset.map(
> > preprocess_function,
> > batched=True,
> > num_proc=12,
> > )
> > training_args = TrainingArguments(
> > output_dir="./evo_results",
> > evaluation_strategy="epoch",
> > learning_rate=2e-5,
> > weight_decay=0.01,
> > gradient_accumulation_steps=2,
> > per_device_train_batch_size=4,
> > warmup_steps=10,
> > max_steps=100, # only a demo
> > logging_steps=10,
> > eval_steps=100,
> > bf16=True
> > # fp16=True, # This didn't work.
> > )
> > trainer = Trainer(
> > model=model,
> > args=training_args,
> > train_dataset=tokenized_ds["train"],
> > eval_dataset=tokenized_ds["test"],
> > data_collator=data_collator,
> > )
> > trainer.train()
> 
> [@JinyuanSun](https://github.com/JinyuanSun) Hi Sun, Thanks for the fine-tuning code. I used your code finetune a model and I got a results folder ./evo_result/checkpoint-100/ Could you show how to read the model from the result and use it for the generation task? I was having some confusion loading the model. Thanks very much!

Hi, after carefully review the code, it may not work as expected to only fine-tune the last layer. It is better to train all the layers. You can ask the authors to open-source the details or scripts and data to reproduce their paper.

**Comment by luiskuhn** [comment]
Hi all,
at the moment I am trying to create a finetuning dataset, and I am wondering how a DNA sequence with the special prompt token should look like. Could you perhaps point me to, or provide an example of how these strings should be constructed, perhaps an example with a couple of CRISPR-Cas loci sequences?
