### ISSUE TITLE
AttributeError: 'InferenceParams' object has no attribute 'fused_ft_kernel'

### ISSUE THREAD

**Issue by qiji24-jlu** [evo-design/evo#57]
when i try use prompt"ACTG" to run generate.py

(evo) qj@supermicro-a526:~/python-project/evo/evo-main$ python -m scripts.generate     --model-name 'evo-1-131k-base'     --prompt ACGT     --n-samples 10     --n-tokens 100     --temperature 1.     --top-k 4     --device cuda:3
/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.47it/s]
Generated sequences:
Traceback (most recent call last):
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/qj/python-project/evo/evo-main/scripts/generate.py", line 67, in <module>
    main()
  File "/home/qj/python-project/evo/evo-main/scripts/generate.py", line 50, in main
    output_seqs, output_scores = generate(
  File "/home/qj/python-project/evo/evo-main/evo/generation.py", line 71, in generate
    output_ids, logits = g.generate(
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/stripedhyena/generation.py", line 111, in generate
    logits, inference_params_dict_out = self.model(
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/stripedhyena/model.py", line 362, in forward
    x, inference_params_dict_out = self.stateful_forward(
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/stripedhyena/model.py", line 377, in stateful_forward
    x, _ = block(x, inference_params=inference_params)
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/stripedhyena/model.py", line 73, in forward
    self.inner_mha_cls(
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj/anaconda3/envs/evo/lib/python3.8/site-packages/flash_attn/modules/mha.py", line 498, in forward
    if (not inference_params.fused_ft_kernel) or inference_params.sequence_len_offset == 0:
AttributeError: 'InferenceParams' object has no attribute 'fused_ft_kernel'
how to solve it

**Comment by qijishinidie** [comment]
i have solved it ,just update flash_attn
